apiVersion: batch/v1
kind: Job
metadata:
  name: mysql-migration-job
  labels:
    app: gestion-produits
    variant: mysql
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name: mysql-migration
        image: mariadb:10.6
        command: ["/bin/bash", "-c"]
        args:
        - |
          apt-get update && 
          apt-get install -y wait-for-it &&
          echo "Waiting for database to be ready..." &&
          wait-for-it -t 120 mysql-service:3306 &&
          echo "Creating database if it doesn't exist..." &&
          mysql -h mysql-service -u root -p$MYSQL_ROOT_PASSWORD -e "CREATE DATABASE IF NOT EXISTS $DB_NAME;" &&
          echo "Running SQL script..." &&
          # Process SQL script to replace any potential hostname references
          cp /docker-entrypoint-initdb.d/gestion_produits.sql /tmp/prepared_script.sql &&
          mysql -h mysql-service -u root -p$MYSQL_ROOT_PASSWORD $DB_NAME < /tmp/prepared_script.sql &&
          echo "Migration completed successfully!"
        envFrom:
        - configMapRef:
            name: mysql-config
        - secretRef:
            name: mysql-secrets
        env:
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: DB_NAME
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: DB_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: DB_PASSWORD
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: MYSQL_ROOT_PASSWORD
        volumeMounts:
        - name: init-sql
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: init-sql
        configMap:
          name: mysql-init-sql
      restartPolicy: OnFailure
