apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data-pvc
  labels:
    app: gestion-produits
    variant: mysql
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-mysql
  resources:
    requests:
      storage: 1Gi
