apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- storage-class.yaml
- pvc.yaml
- uploads-pvc.yaml
- configmap.yaml
- configmap-sql.yaml
- secrets.yaml
- db-deployment.yaml
- db-service.yaml
- migration-job.yaml
- web-deployment.yaml
- web-service.yaml
# Uncomment when you're ready to configure ingress
# - ingress.yaml

namespace: gestion-produits-postgresql

commonLabels:
  app: gestion-produits
  variant: postgresql
